"""
Example script to programatically sweep through a codebase and modify code.
Like a more flexible version of Find-and-Replace.
I'm sure there's some clever way to accomplish the same in one line with a regex.

This example looks for all Enum's (including both enum.Enum and special_enum.SpecialEnum),
and marks them as enum.unique (unless they are already marked).

For example:

```
import enum

+++ @enum.unique
class MyEnumUnmarked(enum.Enum):
    RED = "r"
    GREEN = "g"
    BLUE = "b"

@enum.unique
class MyEnumAlreadyMarked(enum.Enum):
    RED = "r"
    GREEN = "g"
    BLUE = "b"
```

```
+++ import enum
import codebase.types.special_enum as special_enum

+++ @enum.unique
class MySpecialEnum(enum.Enum):
    RED = "r"
    GREEN = "g"
    BLUE = "b"
```
"""

import pathlib


# list every python file in the codebase
for obj in pathlib.Path("/path/to/codebase").rglob("*.py"):
    if not obj.is_file():
        continue
    with open(obj, "r") as f:
        rlines = f.readlines()
    if not rlines:
        continue
    # if autogenerated file, skip
    if rlines[0] == "# Generated by codegen.py\n":
        continue
    wlines = []
    for (r, rline) in enumerate(rlines):
        if (
            # for initial line, will underflow to end -- don't care
            not rlines[r-1] == "@enum.unique\n"
            and rline.startswith("class ")
        ):
            if rline.endswith("enum.Enum):\n"):
                wlines.append("@enum.unique\n")
            if rline.endswith("strenum.StrEnum):\n"):
                if "import enum\n" not in wlines:
                    i = wlines.index("from thm.future import strenum\n")
                    wlines.insert(i, "import enum\n")
                wlines.append("@enum.unique\n")
        wlines.append(rline)
    with open(obj, "w") as f:
        f.writelines(wlines)
